[Appearance]
color_scheme_path=/home/parv/.config/qt6ct/colors/matugen.conf
custom_palette=true
standard_dialogs=default
style=Fusion
stylesheets=/home/parv/.config/qt6ct/qss/matugen-style.qss

[Interface]
stylesheets=/home/parv/.config/qt6ct/qss/matugen-style.qss
