foreground            #e8e8e8
background            #000000
selection_foreground  #000000
selection_background  #b27986
cursor                #b27986
cursor_text_color     #000000
url_color             #b27986

color0                #000000
color8                #101010
color1                #a85858
color9                #a85858
color2                #b27986
color10               #b27986
color3                #a88c5c
color11               #a88c5c
color4                #b27986
color12               #b27986
color5                #e8e8e8
color13               #e8e8e8
color6                #b27986
color14               #b27986
color7                #b8b8b8
color15               #e8e8e8
